### ISSUE TITLE
Lora full layer finetuning

### ISSUE THREAD

**Issue by akashicMarga** [mzbac/mlx-lora#1]
@mzbac in utils instead of nn.Linear it should be nn.QuantizedLinear for QLORA.

**Comment by mzbac** [comment]
> @mzbac in utils instead of nn.Linear it should be nn.QuantizedLinear for QLORA.
Yes, the initial commit only supports full precision. I added qlora support in a later commit https://github.com/mzbac/mlx-lora/blob/main/utils.py#L15

**Comment by mzbac** [comment]
By the way, you can delete "skip lm_head" since mlx now supports adding lora for the lm_head layer. However, I haven't tested its performance yet..https://github.com/mzbac/mlx-lora/blob/main/utils.py#L13-L14

**Comment by akashicMarga** [comment]
ok let me try out both

**Comment by akashicMarga** [comment]
now i am getting this ValueError: Received parameters not in model: lm_head.scales lm_head.biases. in same code.

**Comment by mzbac** [comment]
Would you pull the latest code from the main branch? I just pushed some clean up and included lm_head as part of full linear layers Lora.

**Comment by akashicMarga** [comment]
Working now Thanks!! @mzbac
