### ISSUE TITLE
from mlx_lm.lora import LoRALinear

### ISSUE THREAD

**Issue by hammer-mt** [mzbac/mlx-lora#3]
I'm getting this when I try to run lora.py after installing requirements (M3 macbook):

```
Traceback (most recent call last):
  File "/Users/hammermt/Codes/fine-tuning/mlx-lora/lora.py", line 2, in <module>
    from mlx_lm.lora import LoRALinear
ImportError: cannot import name 'LoRALinear' from 'mlx_lm.lora' (/opt/homebrew/lib/python3.11/site-packages/mlx_lm/lora.py)
```

I tried searching but your code is literally the only place on the internet I can find the line `from mlx_lm.lora import LoRALinear` so I'm stumped.

I can't find LoRALinear in the mlx_lm library: https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/lora.py
It seems to be here in the models of the main package but not sure how to get that into mlx_lm: https://github.com/ml-explore/mlx-examples/blob/3fdf85e79d4c97ed614991dd3277f93af4c2cc0a/lora/models/lora.py#L7

**Comment by mzbac** [comment]
That is outdated code. If you change the import statement to https://github.com/mzbac/mlx-lora/blob/main/lora.py#L2, that should fix the issue.

**Comment by hammer-mt** [comment]
Thanks for the swift response! You're right it started training when I swapped that out. Thanks again for your help.
